### ISSUE TITLE
question: alias functions in MATLAB

### ISSUE THREAD

**Issue by iAnyKey** [sky-s/physical-units-for-matlab#5]
by digging into this repo I've found an interesting way to alias a class specific function trough specifing its empty prototype.
You are doing it with function `scd`, which contains nothing else, than:
```matlab
function v = scd(v,~)
% See also DimVar.scd
``` 
and acts like some kind of shortcut to the class's public function `DimVar.scd`.
Have You got some links, where such behaviour is documented? I was looking for such functionality, but found nothing till now.
Thanks in Advance!
Regards,
Dimitrii

**Comment by sky-s** [comment]
For this example (and I believe others), the purposed of the top-level scd.m function is to avoid an error if a non-DimVar is provided to the function (in which case the class method DimVar.scd is inaccessible).
